//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Fri Dec 19 21:20:49 EST 2025
//
//
// Ports:
// Name                         I/O  size props
// host_AXI4_S_awready            O     1 const
// host_AXI4_S_wready             O     1 const
// host_AXI4_S_bvalid             O     1 const
// host_AXI4_S_bid                O    16 const
// host_AXI4_S_bresp              O     2 const
// host_AXI4_S_arready            O     1 const
// host_AXI4_S_rvalid             O     1 const
// host_AXI4_S_rid                O    16 const
// host_AXI4_S_rdata              O   512 const
// host_AXI4_S_rresp              O     2 const
// host_AXI4_S_rlast              O     1 const
// tohost_interrupts_first        O    64 const
// RDY_tohost_interrupts_first    O     1 const
// RDY_tohost_interrupts_deq      O     1 const
// tohost_interrupts_notEmpty     O     1 const
// RDY_tohost_interrupts_notEmpty  O     1 const
// ddr_A_M_awvalid                O     1 const
// ddr_A_M_awid                   O    16 const
// ddr_A_M_awaddr                 O    64 const
// ddr_A_M_awlen                  O     8 const
// ddr_A_M_awsize                 O     3 const
// ddr_A_M_awburst                O     2 const
// ddr_A_M_awlock                 O     1 const
// ddr_A_M_awcache                O     4 const
// ddr_A_M_awprot                 O     3 const
// ddr_A_M_awqos                  O     4 const
// ddr_A_M_awregion               O     4 const
// ddr_A_M_wvalid                 O     1 const
// ddr_A_M_wdata                  O   512 const
// ddr_A_M_wstrb                  O    64 const
// ddr_A_M_wlast                  O     1 const
// ddr_A_M_bready                 O     1 const
// ddr_A_M_arvalid                O     1 const
// ddr_A_M_arid                   O    16 const
// ddr_A_M_araddr                 O    64 const
// ddr_A_M_arlen                  O     8 const
// ddr_A_M_arsize                 O     3 const
// ddr_A_M_arburst                O     2 const
// ddr_A_M_arlock                 O     1 const
// ddr_A_M_arcache                O     4 const
// ddr_A_M_arprot                 O     3 const
// ddr_A_M_arqos                  O     4 const
// ddr_A_M_arregion               O     4 const
// ddr_A_M_rready                 O     1 const
// ddr_B_M_awvalid                O     1 const
// ddr_B_M_awid                   O    16 const
// ddr_B_M_awaddr                 O    64 const
// ddr_B_M_awlen                  O     8 const
// ddr_B_M_awsize                 O     3 const
// ddr_B_M_awburst                O     2 const
// ddr_B_M_awlock                 O     1 const
// ddr_B_M_awcache                O     4 const
// ddr_B_M_awprot                 O     3 const
// ddr_B_M_awqos                  O     4 const
// ddr_B_M_awregion               O     4 const
// ddr_B_M_wvalid                 O     1 const
// ddr_B_M_wdata                  O   512 const
// ddr_B_M_wstrb                  O    64 const
// ddr_B_M_wlast                  O     1 const
// ddr_B_M_bready                 O     1 const
// ddr_B_M_arvalid                O     1 const
// ddr_B_M_arid                   O    16 const
// ddr_B_M_araddr                 O    64 const
// ddr_B_M_arlen                  O     8 const
// ddr_B_M_arsize                 O     3 const
// ddr_B_M_arburst                O     2 const
// ddr_B_M_arlock                 O     1 const
// ddr_B_M_arcache                O     4 const
// ddr_B_M_arprot                 O     3 const
// ddr_B_M_arqos                  O     4 const
// ddr_B_M_arregion               O     4 const
// ddr_B_M_rready                 O     1 const
// CLK_clk1                       I     1 unused
// CLK_clk2                       I     1 unused
// CLK_clk3                       I     1 unused
// CLK_clk4                       I     1 unused
// CLK_clk5                       I     1 unused
// CLK                            I     1 unused
// RST_N                          I     1 unused
// host_AXI4_S_awvalid            I     1 unused
// host_AXI4_S_awid               I    16 unused
// host_AXI4_S_awaddr             I    64 unused
// host_AXI4_S_awlen              I     8 unused
// host_AXI4_S_awsize             I     3 unused
// host_AXI4_S_awburst            I     2 unused
// host_AXI4_S_awlock             I     1 unused
// host_AXI4_S_awcache            I     4 unused
// host_AXI4_S_awprot             I     3 unused
// host_AXI4_S_awqos              I     4 unused
// host_AXI4_S_awregion           I     4 unused
// host_AXI4_S_wvalid             I     1 unused
// host_AXI4_S_wdata              I   512 unused
// host_AXI4_S_wstrb              I    64 unused
// host_AXI4_S_wlast              I     1 unused
// host_AXI4_S_bready             I     1 unused
// host_AXI4_S_arvalid            I     1 unused
// host_AXI4_S_arid               I    16 unused
// host_AXI4_S_araddr             I    64 unused
// host_AXI4_S_arlen              I     8 unused
// host_AXI4_S_arsize             I     3 unused
// host_AXI4_S_arburst            I     2 unused
// host_AXI4_S_arlock             I     1 unused
// host_AXI4_S_arcache            I     4 unused
// host_AXI4_S_arprot             I     3 unused
// host_AXI4_S_arqos              I     4 unused
// host_AXI4_S_arregion           I     4 unused
// host_AXI4_S_rready             I     1 unused
// ddr_A_M_awready                I     1 unused
// ddr_A_M_wready                 I     1 unused
// ddr_A_M_bvalid                 I     1 unused
// ddr_A_M_bid                    I    16 unused
// ddr_A_M_bresp                  I     2 unused
// ddr_A_M_arready                I     1 unused
// ddr_A_M_rvalid                 I     1 unused
// ddr_A_M_rid                    I    16 unused
// ddr_A_M_rdata                  I   512 unused
// ddr_A_M_rresp                  I     2 unused
// ddr_A_M_rlast                  I     1 unused
// ddr_B_M_awready                I     1 unused
// ddr_B_M_wready                 I     1 unused
// ddr_B_M_bvalid                 I     1 unused
// ddr_B_M_bid                    I    16 unused
// ddr_B_M_bresp                  I     2 unused
// ddr_B_M_arready                I     1 unused
// ddr_B_M_rvalid                 I     1 unused
// ddr_B_M_rid                    I    16 unused
// ddr_B_M_rdata                  I   512 unused
// ddr_B_M_rresp                  I     2 unused
// ddr_B_M_rlast                  I     1 unused
// EN_tohost_interrupts_deq       I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkVirtual_FPGA_DUT(CLK_clk1,
			  CLK_clk2,
			  CLK_clk3,
			  CLK_clk4,
			  CLK_clk5,
			  CLK,
			  RST_N,

			  host_AXI4_S_awvalid,
			  host_AXI4_S_awid,
			  host_AXI4_S_awaddr,
			  host_AXI4_S_awlen,
			  host_AXI4_S_awsize,
			  host_AXI4_S_awburst,
			  host_AXI4_S_awlock,
			  host_AXI4_S_awcache,
			  host_AXI4_S_awprot,
			  host_AXI4_S_awqos,
			  host_AXI4_S_awregion,

			  host_AXI4_S_awready,

			  host_AXI4_S_wvalid,
			  host_AXI4_S_wdata,
			  host_AXI4_S_wstrb,
			  host_AXI4_S_wlast,

			  host_AXI4_S_wready,

			  host_AXI4_S_bvalid,

			  host_AXI4_S_bid,

			  host_AXI4_S_bresp,

			  host_AXI4_S_bready,

			  host_AXI4_S_arvalid,
			  host_AXI4_S_arid,
			  host_AXI4_S_araddr,
			  host_AXI4_S_arlen,
			  host_AXI4_S_arsize,
			  host_AXI4_S_arburst,
			  host_AXI4_S_arlock,
			  host_AXI4_S_arcache,
			  host_AXI4_S_arprot,
			  host_AXI4_S_arqos,
			  host_AXI4_S_arregion,

			  host_AXI4_S_arready,

			  host_AXI4_S_rvalid,

			  host_AXI4_S_rid,

			  host_AXI4_S_rdata,

			  host_AXI4_S_rresp,

			  host_AXI4_S_rlast,

			  host_AXI4_S_rready,

			  tohost_interrupts_first,
			  RDY_tohost_interrupts_first,

			  EN_tohost_interrupts_deq,
			  RDY_tohost_interrupts_deq,

			  tohost_interrupts_notEmpty,
			  RDY_tohost_interrupts_notEmpty,

			  ddr_A_M_awvalid,

			  ddr_A_M_awid,

			  ddr_A_M_awaddr,

			  ddr_A_M_awlen,

			  ddr_A_M_awsize,

			  ddr_A_M_awburst,

			  ddr_A_M_awlock,

			  ddr_A_M_awcache,

			  ddr_A_M_awprot,

			  ddr_A_M_awqos,

			  ddr_A_M_awregion,

			  ddr_A_M_awready,

			  ddr_A_M_wvalid,

			  ddr_A_M_wdata,

			  ddr_A_M_wstrb,

			  ddr_A_M_wlast,

			  ddr_A_M_wready,

			  ddr_A_M_bvalid,
			  ddr_A_M_bid,
			  ddr_A_M_bresp,

			  ddr_A_M_bready,

			  ddr_A_M_arvalid,

			  ddr_A_M_arid,

			  ddr_A_M_araddr,

			  ddr_A_M_arlen,

			  ddr_A_M_arsize,

			  ddr_A_M_arburst,

			  ddr_A_M_arlock,

			  ddr_A_M_arcache,

			  ddr_A_M_arprot,

			  ddr_A_M_arqos,

			  ddr_A_M_arregion,

			  ddr_A_M_arready,

			  ddr_A_M_rvalid,
			  ddr_A_M_rid,
			  ddr_A_M_rdata,
			  ddr_A_M_rresp,
			  ddr_A_M_rlast,

			  ddr_A_M_rready,

			  ddr_B_M_awvalid,

			  ddr_B_M_awid,

			  ddr_B_M_awaddr,

			  ddr_B_M_awlen,

			  ddr_B_M_awsize,

			  ddr_B_M_awburst,

			  ddr_B_M_awlock,

			  ddr_B_M_awcache,

			  ddr_B_M_awprot,

			  ddr_B_M_awqos,

			  ddr_B_M_awregion,

			  ddr_B_M_awready,

			  ddr_B_M_wvalid,

			  ddr_B_M_wdata,

			  ddr_B_M_wstrb,

			  ddr_B_M_wlast,

			  ddr_B_M_wready,

			  ddr_B_M_bvalid,
			  ddr_B_M_bid,
			  ddr_B_M_bresp,

			  ddr_B_M_bready,

			  ddr_B_M_arvalid,

			  ddr_B_M_arid,

			  ddr_B_M_araddr,

			  ddr_B_M_arlen,

			  ddr_B_M_arsize,

			  ddr_B_M_arburst,

			  ddr_B_M_arlock,

			  ddr_B_M_arcache,

			  ddr_B_M_arprot,

			  ddr_B_M_arqos,

			  ddr_B_M_arregion,

			  ddr_B_M_arready,

			  ddr_B_M_rvalid,
			  ddr_B_M_rid,
			  ddr_B_M_rdata,
			  ddr_B_M_rresp,
			  ddr_B_M_rlast,

			  ddr_B_M_rready);
  input  CLK_clk1;
  input  CLK_clk2;
  input  CLK_clk3;
  input  CLK_clk4;
  input  CLK_clk5;
  input  CLK;
  input  RST_N;

  // action method host_AXI4_S_m_awvalid
  input  host_AXI4_S_awvalid;
  input  [15 : 0] host_AXI4_S_awid;
  input  [63 : 0] host_AXI4_S_awaddr;
  input  [7 : 0] host_AXI4_S_awlen;
  input  [2 : 0] host_AXI4_S_awsize;
  input  [1 : 0] host_AXI4_S_awburst;
  input  host_AXI4_S_awlock;
  input  [3 : 0] host_AXI4_S_awcache;
  input  [2 : 0] host_AXI4_S_awprot;
  input  [3 : 0] host_AXI4_S_awqos;
  input  [3 : 0] host_AXI4_S_awregion;

  // value method host_AXI4_S_m_awready
  output host_AXI4_S_awready;

  // action method host_AXI4_S_m_wvalid
  input  host_AXI4_S_wvalid;
  input  [511 : 0] host_AXI4_S_wdata;
  input  [63 : 0] host_AXI4_S_wstrb;
  input  host_AXI4_S_wlast;

  // value method host_AXI4_S_m_wready
  output host_AXI4_S_wready;

  // value method host_AXI4_S_m_bvalid
  output host_AXI4_S_bvalid;

  // value method host_AXI4_S_m_bid
  output [15 : 0] host_AXI4_S_bid;

  // value method host_AXI4_S_m_bresp
  output [1 : 0] host_AXI4_S_bresp;

  // value method host_AXI4_S_m_buser

  // action method host_AXI4_S_m_bready
  input  host_AXI4_S_bready;

  // action method host_AXI4_S_m_arvalid
  input  host_AXI4_S_arvalid;
  input  [15 : 0] host_AXI4_S_arid;
  input  [63 : 0] host_AXI4_S_araddr;
  input  [7 : 0] host_AXI4_S_arlen;
  input  [2 : 0] host_AXI4_S_arsize;
  input  [1 : 0] host_AXI4_S_arburst;
  input  host_AXI4_S_arlock;
  input  [3 : 0] host_AXI4_S_arcache;
  input  [2 : 0] host_AXI4_S_arprot;
  input  [3 : 0] host_AXI4_S_arqos;
  input  [3 : 0] host_AXI4_S_arregion;

  // value method host_AXI4_S_m_arready
  output host_AXI4_S_arready;

  // value method host_AXI4_S_m_rvalid
  output host_AXI4_S_rvalid;

  // value method host_AXI4_S_m_rid
  output [15 : 0] host_AXI4_S_rid;

  // value method host_AXI4_S_m_rdata
  output [511 : 0] host_AXI4_S_rdata;

  // value method host_AXI4_S_m_rresp
  output [1 : 0] host_AXI4_S_rresp;

  // value method host_AXI4_S_m_rlast
  output host_AXI4_S_rlast;

  // value method host_AXI4_S_m_ruser

  // action method host_AXI4_S_m_rready
  input  host_AXI4_S_rready;

  // value method tohost_interrupts_first
  output [63 : 0] tohost_interrupts_first;
  output RDY_tohost_interrupts_first;

  // action method tohost_interrupts_deq
  input  EN_tohost_interrupts_deq;
  output RDY_tohost_interrupts_deq;

  // value method tohost_interrupts_notEmpty
  output tohost_interrupts_notEmpty;
  output RDY_tohost_interrupts_notEmpty;

  // value method ddr_A_M_m_awvalid
  output ddr_A_M_awvalid;

  // value method ddr_A_M_m_awid
  output [15 : 0] ddr_A_M_awid;

  // value method ddr_A_M_m_awaddr
  output [63 : 0] ddr_A_M_awaddr;

  // value method ddr_A_M_m_awlen
  output [7 : 0] ddr_A_M_awlen;

  // value method ddr_A_M_m_awsize
  output [2 : 0] ddr_A_M_awsize;

  // value method ddr_A_M_m_awburst
  output [1 : 0] ddr_A_M_awburst;

  // value method ddr_A_M_m_awlock
  output ddr_A_M_awlock;

  // value method ddr_A_M_m_awcache
  output [3 : 0] ddr_A_M_awcache;

  // value method ddr_A_M_m_awprot
  output [2 : 0] ddr_A_M_awprot;

  // value method ddr_A_M_m_awqos
  output [3 : 0] ddr_A_M_awqos;

  // value method ddr_A_M_m_awregion
  output [3 : 0] ddr_A_M_awregion;

  // value method ddr_A_M_m_awuser

  // action method ddr_A_M_m_awready
  input  ddr_A_M_awready;

  // value method ddr_A_M_m_wvalid
  output ddr_A_M_wvalid;

  // value method ddr_A_M_m_wdata
  output [511 : 0] ddr_A_M_wdata;

  // value method ddr_A_M_m_wstrb
  output [63 : 0] ddr_A_M_wstrb;

  // value method ddr_A_M_m_wlast
  output ddr_A_M_wlast;

  // value method ddr_A_M_m_wuser

  // action method ddr_A_M_m_wready
  input  ddr_A_M_wready;

  // action method ddr_A_M_m_bvalid
  input  ddr_A_M_bvalid;
  input  [15 : 0] ddr_A_M_bid;
  input  [1 : 0] ddr_A_M_bresp;

  // value method ddr_A_M_m_bready
  output ddr_A_M_bready;

  // value method ddr_A_M_m_arvalid
  output ddr_A_M_arvalid;

  // value method ddr_A_M_m_arid
  output [15 : 0] ddr_A_M_arid;

  // value method ddr_A_M_m_araddr
  output [63 : 0] ddr_A_M_araddr;

  // value method ddr_A_M_m_arlen
  output [7 : 0] ddr_A_M_arlen;

  // value method ddr_A_M_m_arsize
  output [2 : 0] ddr_A_M_arsize;

  // value method ddr_A_M_m_arburst
  output [1 : 0] ddr_A_M_arburst;

  // value method ddr_A_M_m_arlock
  output ddr_A_M_arlock;

  // value method ddr_A_M_m_arcache
  output [3 : 0] ddr_A_M_arcache;

  // value method ddr_A_M_m_arprot
  output [2 : 0] ddr_A_M_arprot;

  // value method ddr_A_M_m_arqos
  output [3 : 0] ddr_A_M_arqos;

  // value method ddr_A_M_m_arregion
  output [3 : 0] ddr_A_M_arregion;

  // value method ddr_A_M_m_aruser

  // action method ddr_A_M_m_arready
  input  ddr_A_M_arready;

  // action method ddr_A_M_m_rvalid
  input  ddr_A_M_rvalid;
  input  [15 : 0] ddr_A_M_rid;
  input  [511 : 0] ddr_A_M_rdata;
  input  [1 : 0] ddr_A_M_rresp;
  input  ddr_A_M_rlast;

  // value method ddr_A_M_m_rready
  output ddr_A_M_rready;

  // value method ddr_B_M_m_awvalid
  output ddr_B_M_awvalid;

  // value method ddr_B_M_m_awid
  output [15 : 0] ddr_B_M_awid;

  // value method ddr_B_M_m_awaddr
  output [63 : 0] ddr_B_M_awaddr;

  // value method ddr_B_M_m_awlen
  output [7 : 0] ddr_B_M_awlen;

  // value method ddr_B_M_m_awsize
  output [2 : 0] ddr_B_M_awsize;

  // value method ddr_B_M_m_awburst
  output [1 : 0] ddr_B_M_awburst;

  // value method ddr_B_M_m_awlock
  output ddr_B_M_awlock;

  // value method ddr_B_M_m_awcache
  output [3 : 0] ddr_B_M_awcache;

  // value method ddr_B_M_m_awprot
  output [2 : 0] ddr_B_M_awprot;

  // value method ddr_B_M_m_awqos
  output [3 : 0] ddr_B_M_awqos;

  // value method ddr_B_M_m_awregion
  output [3 : 0] ddr_B_M_awregion;

  // value method ddr_B_M_m_awuser

  // action method ddr_B_M_m_awready
  input  ddr_B_M_awready;

  // value method ddr_B_M_m_wvalid
  output ddr_B_M_wvalid;

  // value method ddr_B_M_m_wdata
  output [511 : 0] ddr_B_M_wdata;

  // value method ddr_B_M_m_wstrb
  output [63 : 0] ddr_B_M_wstrb;

  // value method ddr_B_M_m_wlast
  output ddr_B_M_wlast;

  // value method ddr_B_M_m_wuser

  // action method ddr_B_M_m_wready
  input  ddr_B_M_wready;

  // action method ddr_B_M_m_bvalid
  input  ddr_B_M_bvalid;
  input  [15 : 0] ddr_B_M_bid;
  input  [1 : 0] ddr_B_M_bresp;

  // value method ddr_B_M_m_bready
  output ddr_B_M_bready;

  // value method ddr_B_M_m_arvalid
  output ddr_B_M_arvalid;

  // value method ddr_B_M_m_arid
  output [15 : 0] ddr_B_M_arid;

  // value method ddr_B_M_m_araddr
  output [63 : 0] ddr_B_M_araddr;

  // value method ddr_B_M_m_arlen
  output [7 : 0] ddr_B_M_arlen;

  // value method ddr_B_M_m_arsize
  output [2 : 0] ddr_B_M_arsize;

  // value method ddr_B_M_m_arburst
  output [1 : 0] ddr_B_M_arburst;

  // value method ddr_B_M_m_arlock
  output ddr_B_M_arlock;

  // value method ddr_B_M_m_arcache
  output [3 : 0] ddr_B_M_arcache;

  // value method ddr_B_M_m_arprot
  output [2 : 0] ddr_B_M_arprot;

  // value method ddr_B_M_m_arqos
  output [3 : 0] ddr_B_M_arqos;

  // value method ddr_B_M_m_arregion
  output [3 : 0] ddr_B_M_arregion;

  // value method ddr_B_M_m_aruser

  // action method ddr_B_M_m_arready
  input  ddr_B_M_arready;

  // action method ddr_B_M_m_rvalid
  input  ddr_B_M_rvalid;
  input  [15 : 0] ddr_B_M_rid;
  input  [511 : 0] ddr_B_M_rdata;
  input  [1 : 0] ddr_B_M_rresp;
  input  ddr_B_M_rlast;

  // value method ddr_B_M_m_rready
  output ddr_B_M_rready;

  // signals for module outputs
  wire [511 : 0] ddr_A_M_wdata, ddr_B_M_wdata, host_AXI4_S_rdata;
  wire [63 : 0] ddr_A_M_araddr,
		ddr_A_M_awaddr,
		ddr_A_M_wstrb,
		ddr_B_M_araddr,
		ddr_B_M_awaddr,
		ddr_B_M_wstrb,
		tohost_interrupts_first;
  wire [15 : 0] ddr_A_M_arid,
		ddr_A_M_awid,
		ddr_B_M_arid,
		ddr_B_M_awid,
		host_AXI4_S_bid,
		host_AXI4_S_rid;
  wire [7 : 0] ddr_A_M_arlen, ddr_A_M_awlen, ddr_B_M_arlen, ddr_B_M_awlen;
  wire [3 : 0] ddr_A_M_arcache,
	       ddr_A_M_arqos,
	       ddr_A_M_arregion,
	       ddr_A_M_awcache,
	       ddr_A_M_awqos,
	       ddr_A_M_awregion,
	       ddr_B_M_arcache,
	       ddr_B_M_arqos,
	       ddr_B_M_arregion,
	       ddr_B_M_awcache,
	       ddr_B_M_awqos,
	       ddr_B_M_awregion;
  wire [2 : 0] ddr_A_M_arprot,
	       ddr_A_M_arsize,
	       ddr_A_M_awprot,
	       ddr_A_M_awsize,
	       ddr_B_M_arprot,
	       ddr_B_M_arsize,
	       ddr_B_M_awprot,
	       ddr_B_M_awsize;
  wire [1 : 0] ddr_A_M_arburst,
	       ddr_A_M_awburst,
	       ddr_B_M_arburst,
	       ddr_B_M_awburst,
	       host_AXI4_S_bresp,
	       host_AXI4_S_rresp;
  wire RDY_tohost_interrupts_deq,
       RDY_tohost_interrupts_first,
       RDY_tohost_interrupts_notEmpty,
       ddr_A_M_arlock,
       ddr_A_M_arvalid,
       ddr_A_M_awlock,
       ddr_A_M_awvalid,
       ddr_A_M_bready,
       ddr_A_M_rready,
       ddr_A_M_wlast,
       ddr_A_M_wvalid,
       ddr_B_M_arlock,
       ddr_B_M_arvalid,
       ddr_B_M_awlock,
       ddr_B_M_awvalid,
       ddr_B_M_bready,
       ddr_B_M_rready,
       ddr_B_M_wlast,
       ddr_B_M_wvalid,
       host_AXI4_S_arready,
       host_AXI4_S_awready,
       host_AXI4_S_bvalid,
       host_AXI4_S_rlast,
       host_AXI4_S_rvalid,
       host_AXI4_S_wready,
       tohost_interrupts_notEmpty;

  // value method host_AXI4_S_m_awready
  assign host_AXI4_S_awready = 1'h0 ;

  // value method host_AXI4_S_m_wready
  assign host_AXI4_S_wready = 1'h0 ;

  // value method host_AXI4_S_m_bvalid
  assign host_AXI4_S_bvalid = 1'h0 ;

  // value method host_AXI4_S_m_bid
  assign host_AXI4_S_bid = 16'hAAAA ;

  // value method host_AXI4_S_m_bresp
  assign host_AXI4_S_bresp = 2'h2 ;

  // value method host_AXI4_S_m_arready
  assign host_AXI4_S_arready = 1'h0 ;

  // value method host_AXI4_S_m_rvalid
  assign host_AXI4_S_rvalid = 1'h0 ;

  // value method host_AXI4_S_m_rid
  assign host_AXI4_S_rid = 16'hAAAA ;

  // value method host_AXI4_S_m_rdata
  assign host_AXI4_S_rdata =
	     512'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ;

  // value method host_AXI4_S_m_rresp
  assign host_AXI4_S_rresp = 2'h2 ;

  // value method host_AXI4_S_m_rlast
  assign host_AXI4_S_rlast = 1'h0 ;

  // value method tohost_interrupts_first
  assign tohost_interrupts_first = 64'hAAAAAAAAAAAAAAAA ;
  assign RDY_tohost_interrupts_first = 1'd1 ;

  // action method tohost_interrupts_deq
  assign RDY_tohost_interrupts_deq = 1'd1 ;

  // value method tohost_interrupts_notEmpty
  assign tohost_interrupts_notEmpty = 1'h0 ;
  assign RDY_tohost_interrupts_notEmpty = 1'd1 ;

  // value method ddr_A_M_m_awvalid
  assign ddr_A_M_awvalid = 1'h0 ;

  // value method ddr_A_M_m_awid
  assign ddr_A_M_awid = 16'hAAAA ;

  // value method ddr_A_M_m_awaddr
  assign ddr_A_M_awaddr = 64'hAAAAAAAAAAAAAAAA ;

  // value method ddr_A_M_m_awlen
  assign ddr_A_M_awlen = 8'hAA ;

  // value method ddr_A_M_m_awsize
  assign ddr_A_M_awsize = 3'h2 ;

  // value method ddr_A_M_m_awburst
  assign ddr_A_M_awburst = 2'h2 ;

  // value method ddr_A_M_m_awlock
  assign ddr_A_M_awlock = 1'h0 ;

  // value method ddr_A_M_m_awcache
  assign ddr_A_M_awcache = 4'hA ;

  // value method ddr_A_M_m_awprot
  assign ddr_A_M_awprot = 3'h2 ;

  // value method ddr_A_M_m_awqos
  assign ddr_A_M_awqos = 4'hA ;

  // value method ddr_A_M_m_awregion
  assign ddr_A_M_awregion = 4'hA ;

  // value method ddr_A_M_m_wvalid
  assign ddr_A_M_wvalid = 1'h0 ;

  // value method ddr_A_M_m_wdata
  assign ddr_A_M_wdata =
	     512'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ;

  // value method ddr_A_M_m_wstrb
  assign ddr_A_M_wstrb = 64'hAAAAAAAAAAAAAAAA ;

  // value method ddr_A_M_m_wlast
  assign ddr_A_M_wlast = 1'h0 ;

  // value method ddr_A_M_m_bready
  assign ddr_A_M_bready = 1'h0 ;

  // value method ddr_A_M_m_arvalid
  assign ddr_A_M_arvalid = 1'h0 ;

  // value method ddr_A_M_m_arid
  assign ddr_A_M_arid = 16'hAAAA ;

  // value method ddr_A_M_m_araddr
  assign ddr_A_M_araddr = 64'hAAAAAAAAAAAAAAAA ;

  // value method ddr_A_M_m_arlen
  assign ddr_A_M_arlen = 8'hAA ;

  // value method ddr_A_M_m_arsize
  assign ddr_A_M_arsize = 3'h2 ;

  // value method ddr_A_M_m_arburst
  assign ddr_A_M_arburst = 2'h2 ;

  // value method ddr_A_M_m_arlock
  assign ddr_A_M_arlock = 1'h0 ;

  // value method ddr_A_M_m_arcache
  assign ddr_A_M_arcache = 4'hA ;

  // value method ddr_A_M_m_arprot
  assign ddr_A_M_arprot = 3'h2 ;

  // value method ddr_A_M_m_arqos
  assign ddr_A_M_arqos = 4'hA ;

  // value method ddr_A_M_m_arregion
  assign ddr_A_M_arregion = 4'hA ;

  // value method ddr_A_M_m_rready
  assign ddr_A_M_rready = 1'h0 ;

  // value method ddr_B_M_m_awvalid
  assign ddr_B_M_awvalid = 1'h0 ;

  // value method ddr_B_M_m_awid
  assign ddr_B_M_awid = 16'hAAAA ;

  // value method ddr_B_M_m_awaddr
  assign ddr_B_M_awaddr = 64'hAAAAAAAAAAAAAAAA ;

  // value method ddr_B_M_m_awlen
  assign ddr_B_M_awlen = 8'hAA ;

  // value method ddr_B_M_m_awsize
  assign ddr_B_M_awsize = 3'h2 ;

  // value method ddr_B_M_m_awburst
  assign ddr_B_M_awburst = 2'h2 ;

  // value method ddr_B_M_m_awlock
  assign ddr_B_M_awlock = 1'h0 ;

  // value method ddr_B_M_m_awcache
  assign ddr_B_M_awcache = 4'hA ;

  // value method ddr_B_M_m_awprot
  assign ddr_B_M_awprot = 3'h2 ;

  // value method ddr_B_M_m_awqos
  assign ddr_B_M_awqos = 4'hA ;

  // value method ddr_B_M_m_awregion
  assign ddr_B_M_awregion = 4'hA ;

  // value method ddr_B_M_m_wvalid
  assign ddr_B_M_wvalid = 1'h0 ;

  // value method ddr_B_M_m_wdata
  assign ddr_B_M_wdata =
	     512'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ;

  // value method ddr_B_M_m_wstrb
  assign ddr_B_M_wstrb = 64'hAAAAAAAAAAAAAAAA ;

  // value method ddr_B_M_m_wlast
  assign ddr_B_M_wlast = 1'h0 ;

  // value method ddr_B_M_m_bready
  assign ddr_B_M_bready = 1'h0 ;

  // value method ddr_B_M_m_arvalid
  assign ddr_B_M_arvalid = 1'h0 ;

  // value method ddr_B_M_m_arid
  assign ddr_B_M_arid = 16'hAAAA ;

  // value method ddr_B_M_m_araddr
  assign ddr_B_M_araddr = 64'hAAAAAAAAAAAAAAAA ;

  // value method ddr_B_M_m_arlen
  assign ddr_B_M_arlen = 8'hAA ;

  // value method ddr_B_M_m_arsize
  assign ddr_B_M_arsize = 3'h2 ;

  // value method ddr_B_M_m_arburst
  assign ddr_B_M_arburst = 2'h2 ;

  // value method ddr_B_M_m_arlock
  assign ddr_B_M_arlock = 1'h0 ;

  // value method ddr_B_M_m_arcache
  assign ddr_B_M_arcache = 4'hA ;

  // value method ddr_B_M_m_arprot
  assign ddr_B_M_arprot = 3'h2 ;

  // value method ddr_B_M_m_arqos
  assign ddr_B_M_arqos = 4'hA ;

  // value method ddr_B_M_m_arregion
  assign ddr_B_M_arregion = 4'hA ;

  // value method ddr_B_M_m_rready
  assign ddr_B_M_rready = 1'h0 ;
endmodule  // mkVirtual_FPGA_DUT

